version: '3'

networks:
    db-network:
        external: true

services:
  flyway:
    container_name: sb_flyway
    image: flyway/flyway
    command: >
      -configFiles=/flyway/conf/flyway.config 
      -locations=filesystem:/flyway/sql 
      -connectRetries=60 
      migrate
    volumes:
      - ./sql_versions:/flyway/sql
      - ./docker-flyway.config:/flyway/conf/flyway.config
    networks:
      - db-network
    depends_on:
      - postgres
  postgres:
    container_name: sb_postgres
    image: postgres
    restart: unless-stopped
    ports:
    - "5432:5432"
    volumes:
    - sb_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=silver_bullet_db
    networks:
      - db-network
volumes:
  sb_postgres_data: 