version: '3'

networks:
    db-network:
        external: true

services:
  flyway:
    container_name: sb_flyway
    image: flyway/flyway
    command: >
      -configFiles=/flyway/conf/flyway.config 
      -locations=filesystem:/flyway/sql 
      -connectRetries=60 
      info
    volumes:
      - ${PWD}/sql_versions:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    networks:
      - db-network
