version: '3'

networks:
    db-network:
        external: true

services:
  postgres:
    container_name: sb_postgres
    image: postgres
    restart: unless-stopped
    ports:
    - "5432:5432"
    volumes:
    - sb_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=silver_bullet_db
    networks:
      - db-network
volumes:
  sb_postgres_data: 